#!/usr/bin/env bash

echo "Creating database go-bootstrap..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database go-bootstrap-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://tbruyelle@localhost:5432/go-bootstrap-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
